import pandas as pd
import numpy as np
pd.options.display.float_format="{:,.2f}".format
source_file="进阶财务数据练习.xlsx"
df=pd.read_excel(source_file)
df.info()
#统一税率格式
df["税率"]=df["税率"].astype(str).str.replace(r'[^\d.]',"",regex=True)
df["税率"]=pd.to_numeric(df["税率"],errors="coerce")
df["税率"]=df["税率"].fillna(0.0)
#填充备注缺失值
df["备注"]=df["备注"].astype(str).str.strip().replace(r'^\s*$',pd.NA,regex=True)
df["备注"]=df["备注"].replace(["nan","none","null","None"],pd.NA)
df["备注"]=df["备注"].fillna("无")
#统一日期格式
df["交易日期"]=pd.to_datetime(df["交易日期"],errors="coerce")
print(df["交易日期"].dtype)
#统一金额格式
df["金额"]=df["金额"].astype(str).str.replace(r'[^\d.]',"",regex=True)
df["金额"]=pd.to_numeric(df["金额"],errors="coerce").round(2)
df["金额"]=df["金额"].fillna(0.0)
#统一联系电话
df["联系电话"]=df["联系电话"].astype(str).str.replace(r'[^\d]',"",regex=True)
df["联系电话"]=df["联系电话"].replace("",pd.NA)
df["联系电话"]=df["联系电话"].fillna("未提供")
#统一发票号码
df["发票号码"]=df["发票号码"].astype(str).str.replace(r'[^\d]',"",regex=True)
df["发票号码"]=df["发票号码"].replace("",pd.NA)
df["发票号码"]=df["发票号码"].fillna("空")
#统一状态、所属部门
df["状态"]=df["状态"].astype(str).replace({"processing":"处理中","paid":"已支付","cancelled":"已取消","pending":"未支付"})
df["所属部门"]=df["所属部门"].astype(str).replace({"Sales":"销售部","Finance":"财务部","Tech":"技术部","HR":"人事部","Marketing":"市场部"})
print(df.isnull().sum())
dept_cost=df.groupby("所属部门")["金额"].sum().round(2)
print(dept_cost)
df["月份"]=df["交易日期"].dt.to_period("M").astype(str)
monthly_sales=df.groupby("月份")["金额"].sum().round(2)
print(monthly_sales)
status_summary=df.groupby("状态")["金额"].agg(订单金额合计="sum",订单数量="count").round(2)
print(status_summary)
df.to_excel("进阶财务数据练习清洗后数据.xlsx",index=False)